openapi: 3.0.0
info:
  title: Movie Backend API
  description: API documentation cho ứng dụng Movie Backend
  version: 1.0.0
  contact:
    email: your-email@example.com

servers:
  - url: http://localhost:3003
    description: Development server
  - url: https://backend-app-lou3.onrender.com
    description: Production server

tags:
  - name: Authentication
    description: Các API liên quan đến xác thực người dùng (/api/auth)
  - name: User
    description: Các API liên quan đến thông tin người dùng (/api/users)
  - name: Movie
    description: Các API liên quan đến phim (/api/movies)
  - name: Episode
    description: Các API liên quan đến tập phim (/api/episodes)
  - name: Favorite
    description: Các API liên quan đến danh sách yêu thích (/api/favorites)
  - name: Payment
    description: Các API liên quan đến thanh toán (/api/payments)
  - name: Rating
    description: Các API liên quan đến đánh giá (/api/ratings)
  - name: Genre
    description: Các API liên quan đến thể loại phim (/api/genres)

paths:
  /api/auth/register/send-otp:
    post:
      tags:
        - Authentication
      summary: Gửi mã OTP đăng ký
      description: |
        Gửi mã OTP đến số điện thoại để bắt đầu quá trình đăng ký.
        - Mã OTP sẽ được gửi qua SMS
        - OTP có 6 số
        - Định dạng số điện thoại:
          - Bắt đầu bằng 0 hoặc +84
          - Chỉ chứa số, không có ký tự đặc biệt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PhoneRequest'
      responses:
        '200':
          description: Gửi OTP thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                status: "success"
                message: "Vui lòng xác thực số điện thoại của bạn"
                data:
                  phone: "0912345678"
        '400':
          description: Lỗi validate số điện thoại
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: "error"
                message: "Số điện thoại không hợp lệ"
        '429':
          description: Vượt quá số lần gửi OTP cho phép
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: "error"
                message: "Vui lòng thử lại sau"

  /api/auth/register/verify-otp:
    post:
      tags:
        - Authentication
      summary: Xác thực OTP đăng ký
      description: |
        Xác thực mã OTP đã gửi đến số điện thoại.
        - OTP phải đúng với mã đã gửi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyOTPRequest'
      responses:
        '200':
          description: Xác thực OTP thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                status: "success"
                message: "Xác thực OTP thành công"
        '400':
          description: Mã OTP không hợp lệ hoặc đã hết hạn
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: "error"
                message: "Mã OTP không hợp lệ hoặc đã hết hạn"

  /api/auth/register/complete:
    post:
      tags:
        - Authentication
      summary: Hoàn tất đăng ký
      description: |
        Hoàn tất quá trình đăng ký sau khi đã xác thực số điện thoại.
        Yêu cầu:
        - Số điện thoại đã được xác thực OTP
        - Điền đầy đủ thông tin bắt buộc
        - Đăng ký xong sẽ cấp phát access token và refresh token 
        => fontend có thể vào màn hình chính luôn không cần đăng nhập lại 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Lỗi validate dữ liệu hoặc email đã tồn tại
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: "error"
                message: "Email đã được sử dụng"

  /api/auth/login/send-otp:
    post:
      tags:
        - Authentication
      summary: Gửi mã OTP đăng nhập
      description: |
        Gửi mã OTP đến số điện thoại để đăng nhập.
        - Đăng nhập khi đăng xuất hoặc người dùng chưa đăng nhập vào app.
        - Số điện thoại phải đã được đăng ký.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PhoneRequest'
      responses:
        '200':
          description: Gửi OTP thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                status: "success"
                message: "Đã gửi mã OTP đăng nhập"
                data:
                  phone: "0912345678"
        '404':
          description: Số điện thoại chưa đăng ký
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: "error"
                message: "Số điện thoại chưa được đăng ký"

  /api/auth/login/verify:
    post:
      tags:
        - Authentication
      summary: Xác thực OTP và đăng nhập
      description: |
        Xác thực mã OTP để đăng nhập.
        Nếu thành công:
        - Trả về thông tin user
        - Trả về access token và refresh token
        - Token có hiệu lực 24h
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyOTPRequest'
      responses:
        '200':
          description: Đăng nhập thành công
          headers:
            Authorization:
              schema:
                type: string
              description: 'Access token để sử dụng cho các API được bảo vệ'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Mã OTP không hợp lệ hoặc đã hết hạn
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/users/profile:
    get:
      tags:
        - User
      summary: Lấy thông tin profile (phải có token hợp lệ)
      description: Lấy thông tin chi tiết của user đang đăng nhập 
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Lấy thông tin thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
        '401':
          description: Chưa đăng nhập hoặc token không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: "error"
                message: "Unauthorized"

    put:
      tags:
        - User
      summary: Cập nhật profile  (phải có token hợp lệ)
      description: |
        Cập nhật thông tin cá nhân của user đang đăng nhập
        Các trường có thể cập nhật:
        - Họ và tên (full_name)
        - Giới tính (gender: male/female)
        - Ảnh đại diện (avatar: URL hoặc null để xóa)
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
              example:
                status: "success"
                message: "Cập nhật profile thành công"
                data:
                  user:
                    _id: "60d5ecb74f86f45f5c5e2c2e"
                    full_name: "Nguyễn Văn A"
                    email: "example@gmail.com"
                    phone: "0912345678"
                    gender: "male"
                    avatar: "https://example.com/avatar.jpg"
                    is_phone_verified: true
        '400':
          description: Lỗi validate dữ liệu
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: "error"
                message: "Giới tính không hợp lệ"
        '401':
          description: Chưa đăng nhập hoặc token không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: "error"
                message: "Unauthorized"

components:
  schemas:
    PhoneRequest:
      type: object
      required:
        - phone
      properties:
        phone:
          type: string
          example: "0912345678"
          description: |
            Số điện thoại của người dùng
            - Format: 0xxxxxxxxx hoặc +84xxxxxxxxx
            - Phải là số điện thoại Việt Nam hợp lệ
            - Không được chứa ký tự đặc biệt hoặc khoảng trắng

    VerifyOTPRequest:
      type: object
      required:
        - phone
        - otp
      properties:
        phone:
          type: string
          example: "0912345678"
          description: Số điện thoại đã dùng để nhận OTP
        otp:
          type: string
          example: "123456"
          description: Mã OTP 6 số nhận được qua SMS

    RegisterRequest:
      type: object
      required:
        - full_name
        - email
        - gender
      properties:
        full_name:
          type: string
          example: "Nguyễn Văn A"
          description: Họ và tên người dùng
        email:
          type: string
          format: email
          example: "example@gmail.com"
          description: Email người dùng (phải là email hợp lệ và chưa được sử dụng)
        gender:
          type: string
          enum: [male, female]
          example: "male"
          description: Giới tính (male = Nam, female = Nữ)

    UpdateProfileRequest:
      type: object
      properties:
        full_name:
          type: string
          example: "Nguyễn Văn A"
          description: "Họ và tên người dùng"
        gender:
          type: string
          enum: [male, female]
          example: "male"
          description: "Giới tính (male = Nam, female = Nữ)"
        avatar:
          type: string
          example: "https://example.com/avatar.jpg"
          description: "URL ảnh đại diện (null để xóa avatar)"

    AuthResponse:
      type: object
      properties:
        status:
          type: string
          example: "success"
        message:
          type: string
        data:
          type: object
          properties:
            user:
              $ref: '#/components/schemas/UserInfo'
            tokens:
              type: object
              properties:
                access_token:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                refresh_token:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

    ProfileResponse:
      type: object
      properties:
        status:
          type: string
          example: "success"
        data:
          type: object
          properties:
            user:
              $ref: '#/components/schemas/UserInfo'

    UserInfo:
      type: object
      properties:
        _id:
          type: string
          example: "60d5ecb74f86f45f5c5e2c2e"
        full_name:
          type: string
          example: "Nguyễn Văn A"
        email:
          type: string
          example: "example@gmail.com"
        phone:
          type: string
          example: "0912345678"
        gender:
          type: string
          example: "male"
        avatar:
          type: string
          example: "https://example.com/avatar.jpg"
        is_phone_verified:
          type: boolean
          example: true

    SuccessResponse:
      type: object
      properties:
        status:
          type: string
          example: "success"
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: "error"
        message:
          type: string
          example: "Lỗi xử lý yêu cầu"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'JWT token được trả về sau khi đăng nhập thành công. Format: Bearer {token}'