openapi: 3.0.0
info:
  title: Movie App API Documentation
  version: 1.0.0
  description: Combined API documentation for Movie App

servers:
  - url: 'http://localhost:3003'
    description: 'Development server'
  - url: 'https://backend-app-lou3.onrender.com'
    description: 'Production server'

paths:
  /api/movies/{id}/related:
    get:
      tags:
        - Movie
      summary: 'Lấy danh sách phim liên quan dựa trên thể loại cha'
      description: |
        Lấy danh sách phim có cùng thể loại cha với phim được chọn.
        - Mặc định sẽ lấy phim cùng thể loại cha của phim gốc
        - Có thể tắt tính năng lấy theo thể loại cha bằng useParentGenres=false
        - Có thể chỉ định thể loại cụ thể qua query parameter genreIds
        - Trả về tối đa 8 phim liên quan
      parameters:
        - in: path
          name: id
          description: 'ID của phim cần lấy phim liên quan'
          required: true
          schema:
            type: string
        - in: query
          name: genreIds
          description: 'ID của các thể loại muốn lọc, phân cách bằng dấu phẩy (ví dụ: id1,id2,id3)'
          required: false
          schema:
            type: string
        - in: query
          name: useParentGenres
          description: 'Có sử dụng thể loại cha để tìm phim liên quan không (mặc định: true)'
          required: false
          schema:
            type: string
            enum: ['true', 'false']
            default: 'true'
      responses:
        '200':
          description: 'Lấy danh sách phim liên quan thành công'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: '6847d080101e640d01a0c37f'
                        movie_title:
                          type: string
                          example: 'Blue Lock'
                        poster_path:
                          type: string
                          example: 'https://example.com/poster.jpg'
                        movie_type:
                          type: string
                          enum: ['Phim lẻ', 'Phim bộ']
                          example: 'Phim bộ'
                        producer:
                          type: string
                          example: 'Studio XYZ'
                        genres:
                          type: array
                          items:
                            type: object
                            properties:
                              _id:
                                type: string
                                example: '6847d080101e640d01a0c37f'
                              genre_name:
                                type: string
                                example: 'Hoạt hình'
                              parent_genre:
                                type: object
                                properties:
                                  _id:
                                    type: string
                                    example: '6847d080101e640d01a0c37e'
                                  genre_name:
                                    type: string
                                    example: 'Phim Châu Á'
        '404':
          description: 'Không tìm thấy phim'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: 'Không tìm thấy phim'
        '500':
          description: 'Lỗi server'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: 'Lỗi server'
                  error:
                    type: string
                    example: 'Internal server error'

components:
  schemas: {}

tags:
  - name: Movie
    description: Movie management APIs 